restClient:
  movieInfoUrl: http://localhost:8090/v1/movieInfos
  movieReviewUrl: http://localhost:8080/v1/review
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile:
        - local

  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

  main:
    banner-mode: off


